- name: Update cache
  ansible.builtin.apt:
    update_cache: true

- name: Check MicroK8s
  ansible.builtin.command: microk8s status --wait-ready
  register: microk8s_check
  ignore_errors: true
  changed_when: microk8s_check.rc == 0

- name: Install MicroK8s
  community.general.snap:
    name: microk8s
    classic: true
    state: present
  when: microk8s_check.failed

- name: Allow iptables FORWARD policy
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: true

- name: Start MicroK8s
  ansible.builtin.command: microk8s start
  changed_when: false
