services:
  model-service:
    image: "ghcr.io/remla24-02/model_service:stable"
    container_name: model-service
    ports:
      - "5001:5001"
    command: python ./app/main.py

  app:
    image: "ghcr.io/remla24-02/app:stable"
    container_name: app
    ports:
      - "5000:5000"
    environment:
      - MODEL_SERVICE_URL=http://172.17.0.1:5001
    depends_on:
      - model-service
    command: python manage.py runserver 0.0.0.0:5000
