- name: Enable dns
  ansible.builtin.command: microk8s enable dns
  changed_when: false

- name: Enable dashboard
  ansible.builtin.command: microk8s enable dashboard
  changed_when: false

- name: Enable Helm
  ansible.builtin.command: microk8s enable helm
  changed_when: false

- name: Enable host access
  ansible.builtin.command: microk8s enable host-access
  changed_when: false

# For a later assignment (not tested yet, don't just activate)
# - name: Enable Istio
#   command: sudo microk8s enable istio

- name: Copy Kubernetes directory to target hosts
  ansible.builtin.copy:
    src: ../../../../kubernetes/
    dest: /tmp/kubernetes/
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Check for monitoring namespace
  ansible.builtin.command: microk8s kubectl get namespace monitoring
  register: monitoring_namespace_check
  ignore_errors: true
  changed_when: false

- name: Create monitoring namespace
  ansible.builtin.command: microk8s kubectl create namespace monitoring
  when: monitoring_namespace_check.failed
  changed_when: false
