- name: Enable microk8s modules
  ansible.builtin.command: microk8s enable {{ item }}
  with_items:
    - dns
    - dashboard
    - helm
    - host-access
    - ingress
    - community
    - istio
  become: true
  changed_when: false
  register: enabled_microk8s_modules
  until: enabled_microk8s_modules.rc == 0
  retries: 3

- name: Enable MetalLB
  ansible.builtin.command: "microk8s enable metallb {{ ip_range }}"
  become: true
  changed_when: false
  register: enabled_metallb
  until: enabled_metallb.rc == 0
  retries: 3
  vars:
    ip_range: "192.168.58.240-192.168.58.250"

- name: Copy Kubernetes directory to target hosts
  ansible.builtin.copy:
    src: ../../../../kubernetes/
    dest: /tmp/kubernetes/
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Apply Istio Gateways
  ansible.builtin.command: microk8s kubectl apply -f /tmp/kubernetes/{{ item }}
  with_items:
    - gateway.yml
    - addons/istio-gateway.yml
  become: true
  changed_when: false
  register: gateway_applied
  until: gateway_applied.rc == 0
  retries: 3

- name: Enable kubernetes dashboard
  ansible.builtin.command: microk8s kubectl apply -f /tmp/kubernetes/kubernetes-dashboard.yml
  become: true
  changed_when: false
  register: dashboard_applied
  until: dashboard_applied.rc == 0
  retries: 3
