- name: Start cluster
  shell: minikube start --driver=docker

- name: Configure kubectl
  command: minikube kubectl -- get nodes
  register: kubectl_check

- name: Set KUBECONFIG environment variable
  lineinfile:
    path: /home/$USER/.bashrc
    line: "export KUBECONFIG=/home/$USER/.kube/config"
  when: kubectl_check.failed

- name: Enable dashboard addon
  shell: minikube addons enable dashboard
