- name: Check for Grafana
  ansible.builtin.shell: microk8s helm list -q -n monitoring | grep grafana
  register: grafana_check
  failed_when: grafana_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Add Grafana repo
  ansible.builtin.command:
    cmd: microk8s helm repo add grafana https://grafana.github.io/helm-charts
  when: grafana_check.failed
  changed_when: false

- name: Update helm repo
  ansible.builtin.command:
    cmd: microk8s helm repo update
  when: grafana_check.failed
  changed_when: false

- name: Install Grafana
  ansible.builtin.command:
    cmd: microk8s helm install grafana grafana/grafana -n monitoring --create-namespace
  when: grafana_check.failed
  changed_when: false

- name: Check for Grafana dashboard
  ansible.builtin.command:
    cmd: microk8s kubectl get svc grafana-dashboard -n monitoring
  register: grafana_dashboard_check
  changed_when: false
  ignore_errors: true

- name: Expose Grafana dashboard
  ansible.builtin.command:
    cmd: microk8s kubectl expose svc grafana --type=NodePort --target-port=3000 --name=grafana-dashboard -n monitoring
  when: grafana_dashboard_check.failed
  changed_when: false
