- name: Start cluster
  shell: minikube start --driver=docker

- name: Configure kubectl
  command: minikube kubectl get nodes
  register: kubectl_check

- name: Set KUBECONFIG environment variable
  lineinfile:
    path: /home/$USER/.bashrc
    line: "export KUBECONFIG=/home/$USER/.kube/config"
  when: kubectl_check.failed

- name: Enable dashboard addon
  shell: minikube addons enable dashboard

- name: Check for monitoring namespace
  command: kubectl get namespace monitoring
  register: monitoring_namespace_check
  ignore_errors: true

- name: Create monitoring namespace
  shell: kubectl create namespace monitoring
  when: monitoring_namespace_check.failed

- name: Generate Kubeadm join command
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_command

- name: Store Kubeadm join command
  copy:
    content: "{{ kubeadm_join_command.stdout }}"
    dest: /home/$USER/kubeadm_join_command.txt
