- name: Generate join command
  ansible.builtin.command: "microk8s add-node"
  register: join_command
  delegate_to: controller
  ignore_unreachable: false
  changed_when: false

- name: Check join command
  ansible.builtin.set_fact:
    join_command_available: "{{ not join_command.unreachable is defined | default(true) }}"
  when: join_command.rc == 0
  changed_when: false

- name: Extract join command
  ansible.builtin.set_fact:
    join_command: "{{ join_command.stdout_lines | select('search', 'microk8s join ' ~ controller_ip) | list | first }} --worker"
  when: join_command_available
  changed_when: false

- name: Magic delay
  ansible.builtin.pause:
    seconds: 5
  when: join_command_available
  changed_when: false 

- name: Run join command
  ansible.builtin.command: "{{ join_command }}"
  when: join_command_available
  changed_when: false

- name: Magic delay 2
  ansible.builtin.pause:
    seconds: 5
  when: join_command_available
  changed_when: false 
