- name: Generate join command
  command: microk8s add-node
  register: join_command
  delegate_to: controller
  ignore_unreachable: yes

- name: Check join command
  set_fact:
    join_command_available: "{{ not join_command.unreachable is defined | default(true) }}"

- name: Extract join command
  set_fact:
    join_command: "{{ join_command.stdout_lines | select('search', 'microk8s join ' ~ controller_ip) | list | first }} --worker"
  when: join_command_available

- name: Run join command
  command: "{{ join_command }}"
  when: join_command_available
