- name: Get kube config
  ansible.builtin.command: cat /var/snap/microk8s/current/credentials/client.config
  register: controller_config
  changed_when: false

- name: Save kube config
  ansible.builtin.copy:
    content: "{{ controller_config.stdout }}"
    dest: /vagrant/microk8s-config
    mode: "0600"

- name: Fix kube config server address
  ansible.builtin.replace:
    path: /vagrant/microk8s-config
    regexp: 'server: https://127\.0\.0\.1:'
    replace: "server: https://{{ controller_ip }}:"
