apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: istio-system
data:
  config.yaml: |
    domain: app-ratelimit
    descriptors:
      - key: user
        rate_limit:
          unit: minute
          requests_per_unit: 10