apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-rules
  namespace: monitoring
  labels:
    role: alert-rules
spec:
  groups:
    - name: app_rules
      rules:
        - alert: HighRequestRate
          expr: rate(http_requests_total[1m]) > 15
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: High request rate
            description: Request rate is above 15 for more than 2 minutes.
        - alert: HighMemoryUsage
          expr: node_memory_Active_bytes / node_memory_MemTotal_bytes * 100 > 90
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: High Memory Usage
            description: Memory usage is above 90% for more than 2 minutes.
