- name: Check for ConfigMap
  ansible.builtin.shell: microk8s kubectl get configmap | grep model-service-config
  register: configmap_check
  failed_when: configmap_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Apply Model Service ConfigMap
  ansible.builtin.command:
    cmd: microk8s kubectl apply -f /tmp/kubernetes/configmaps/model-service-configmap.yml
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  when: configmap_check.failed
  changed_when: false

- name: Check for Model Service Deployment
  ansible.builtin.shell: microk8s kubectl get deployments | grep model-service-depl
  register: model_service_check
  failed_when: model_service_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Apply Model Service Deployment
  ansible.builtin.command:
    cmd: microk8s kubectl apply -f /tmp/kubernetes/deployments/model-service-deployment.yml
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  when: model_service_check.failed
  changed_when: false

- name: Check for Model Service Service
  ansible.builtin.shell: microk8s kubectl get services | grep model-service-serv
  register: model_service_service_check
  failed_when: model_service_service_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Apply Model Service
  ansible.builtin.command:
    cmd: microk8s kubectl apply -f /tmp/kubernetes/services/model-service-service.yml
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  when: model_service_service_check.failed
  changed_when: false

- name: Check for App Deployment
  ansible.builtin.shell: microk8s kubectl get deployments | grep app-depl
  register: app_check
  failed_when: app_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Apply App Deployment
  ansible.builtin.command:
    cmd: microk8s kubectl apply -f /tmp/kubernetes/deployments/app-deployment.yml
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  when: app_check.failed
  changed_when: false

- name: Check for App Service
  ansible.builtin.shell: microk8s kubectl get services | grep app-serv
  register: app_service_check
  failed_when: app_service_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Apply App Service
  ansible.builtin.command:
    cmd: microk8s kubectl apply -f /tmp/kubernetes/services/app-service.yml
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  when: app_service_check.failed
  changed_when: false

- name: Check for Ingress
  ansible.builtin.shell: microk8s kubectl get ingress | grep app-ingress
  register: ingress_check
  failed_when: ingress_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Apply Ingress
  ansible.builtin.command:
    cmd: microk8s kubectl apply -f /tmp/kubernetes/ingress/ingress.yml
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  when: ingress_check.failed
  changed_when: false
