- name: Deploy Model Service
  ansible.builtin.command:
    cmd: microk8s kubectl apply -f /tmp/kubernetes/model-service.yml
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  changed_when: false
  register: model_service_applied
  until: model_service_applied.rc == 0
  retries: 3

- name: Deploy App
  ansible.builtin.command:
    cmd: microk8s kubectl apply -f /tmp/kubernetes/app.yml
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  changed_when: false
  register: deployment_applied
  until: deployment_applied.rc == 0
  retries: 3

- name: Wait for deployment to be running
  vars:
    services:
      - model-service-stable
      - model-service-canary
      - app-stable
      - app-canary
  ansible.builtin.command:
    cmd: |
      microk8s kubectl rollout status deployment/{{ item }}
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  register: rollout_status
  until: rollout_status.stdout.find("successfully rolled out") != -1
  retries: 20
  delay: 20
  changed_when: false
  with_items: "{{ services }}"
