{
 "title": "Main App Dashboard",
 "description": "Visualization of the Prometheus statistics gathered from the main deployment of the frontend.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Predictions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prediction Accuracy",
   "type": "timeseries",
   "description": "The average accuracy of the predictions as reported by the users over time in one hour windows.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(prediction_accuracy{app=\"app\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Returned predictions",
   "type": "bargauge",
   "description": "The total number of safe and phishing predictions returned.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "safe_url_count_total{app=\"app\"}",
     "legendFormat": "Safe URLs"
    },
    {
     "expr": "phishing_url_count_total{app=\"app\"}",
     "legendFormat": "Phishing URLs"
    },
    {
     "expr": "user_feedback_correct_total{app=\"app\"}",
     "legendFormat": "User reported correct prediction"
    },
    {
     "expr": "user_feedback_incorrect_total{app=\"app\"}",
     "legendFormat": "User reported incorrect prediction"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "bargauge",
   "description": "Amount of requests that where completed in or under a specific amount of seconds. +Inf encompasses is the total amount of requests made.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(request_duration_milliseconds_bucket{app=\"app\"}) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_duration_milliseconds_sum{app=\"app\"} / request_duration_milliseconds_count{app=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}