{
 "title": "Experiment Dashboard",
 "description": "Visualization of the Prometheus statistics gathered from the main deployment of the frontend.",
 "time": { "from": "2024-06-26T12:50:52.424Z", "to": "2024-06-26T12:56:12.912Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Request counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "request_count_total{app=\"app\"}",
     "legendFormat": "Request count (stable)"
    },
    {
     "expr": "request_count_total{app=\"app\"}",
     "legendFormat": "Request count (change to canary)"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_duration_milliseconds_sum{app=\"app\"} / request_duration_milliseconds_count{app=\"app\"}",
     "legendFormat": "Stable"
    },
    {
     "expr": "request_duration_milliseconds_sum{app=\"app\"} / request_duration_milliseconds_count{app=\"app\"}",
     "legendFormat": "Change to canary"
    }
   ]
  },
  {
   "title": "Request duration (stable)",
   "type": "bargauge",
   "description": "Amount of requests that where completed in or under a specific amount of seconds. +Inf encompasses is the total amount of requests made.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(request_duration_milliseconds_bucket{app=\"app\"}) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total feedback given",
   "type": "bargauge",
   "description": "Check if users are more inclined to give feedback when using the canary release.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "safe_url_count_total{app=\"app\"} + phishing_url_count_total{app=\"app\"}",
     "legendFormat": "Total feedback (stable)"
    },
    {
     "expr": "safe_url_count_total{app=\"app\"} + phishing_url_count_total{app=\"app\"}",
     "legendFormat": "Total feedback (canary)"
    }
   ]
  },
  {
   "title": "Request duration (change to canary)",
   "type": "bargauge",
   "description": "Amount of requests that where completed in or under a specific amount of seconds. +Inf encompasses is the total amount of requests made.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(request_duration_milliseconds_bucket{app=\"app\"}) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}