- name: Add Prometheus repo
  ansible.builtin.command:
    cmd: microk8s helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  changed_when: false

- name: Update helm repo
  ansible.builtin.command:
    cmd: microk8s helm repo update
  changed_when: false

- name: Check for Prometheus
  ansible.builtin.shell: microk8s kubectl get crd | grep prometheus
  register: prometheus_crd_check
  failed_when: prometheus_crd_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Install Prometheus
  ansible.builtin.command:
    cmd: microk8s helm install prometheus prometheus-community/kube-prometheus-stack  -n monitoring -f /tmp/kubernetes/helm/prometheus-values.yml
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  when: prometheus_crd_check.failed
  changed_when: false

- name: Apply Prometheus ConfigMap
  ansible.builtin.command:
    cmd: microk8s kubectl apply -f /tmp/kubernetes/configmaps/prometheus-configmap.yml
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  changed_when: false

- name: Apply PrometheusRule
  ansible.builtin.command:
    cmd: microk8s kubectl apply -f /tmp/kubernetes/rules/prometheus-rules.yml
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  changed_when: false

- name: Expose Prometheus deployment
  ansible.builtin.command:
    cmd: microk8s kubectl expose deployment prometheus-kube-prometheus-operator --type=NodePort --name=prometheus-service --namespace=monitoring --port=9090 --target-port=9090
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  changed_when: false

- name: Expose Grafana deployment
  ansible.builtin.command:
    cmd: microk8s kubectl expose deployment prometheus-grafana --type=NodePort --name=grafana-service --namespace=monitoring --port=3000 --target-port=3000
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  changed_when: false
