- name: Add Prometheus repo
  ansible.builtin.command:
    cmd: microk8s helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  changed_when: false

- name: Update helm repo
  ansible.builtin.command:
    cmd: microk8s helm repo update
  changed_when: false

- name: Install/upgrade Prometheus using microk8s helm
  ansible.builtin.command:
    cmd: >
      microk8s helm upgrade --install prometheus prometheus-community/kube-prometheus-stack
      --values /tmp/kubernetes/helm/prometheus-values.yml
      -n monitoring
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  changed_when: false

- name: Apply Prometheus ConfigMap
  ansible.builtin.command:
    cmd: microk8s kubectl apply -f /tmp/kubernetes/configmaps/prometheus-configmap.yml
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  changed_when: false

- name: Apply PrometheusRule
  ansible.builtin.command:
    cmd: microk8s kubectl apply -f /tmp/kubernetes/rules/prometheus-rules.yml
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  changed_when: false

- name: Check Prometheus exposed
  ansible.builtin.shell: microk8s kubectl get svc -n monitoring | grep prometheus-service
  register: prometheus_exposed_check
  failed_when: prometheus_exposed_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Expose Prometheus deployment
  ansible.builtin.command:
    cmd: >
      microk8s kubectl expose service prometheus-kube-prometheus-prometheus --type=NodePort --name=prometheus-service
      -n monitoring --port=9090 --target-port=9090
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  when: prometheus_exposed_check.failed
  changed_when: false

- name: Check Grafana exposed
  ansible.builtin.shell: microk8s kubectl get svc -n monitoring | grep grafana-service
  register: grafana_exposed_check
  failed_when: grafana_exposed_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Expose Grafana deployment
  ansible.builtin.command:
    cmd: >
      microk8s kubectl expose deployment prometheus-grafana --type=NodePort --name=grafana-service
        -n monitoring --port=3000 --target-port=3000
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  when: grafana_exposed_check.failed
  changed_when: false

- name: Apply Prometheus Ingress
  ansible.builtin.command:
    cmd: microk8s kubectl apply -f /tmp/kubernetes/ingress/prometheus-ingress.yml
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  changed_when: false

- name: Apply Grafana Ingress
  ansible.builtin.command:
    cmd: microk8s kubectl apply -f /tmp/kubernetes/ingress/grafana-ingress.yml
  environment:
    KUBECONFIG: /vagrant/microk8s-config
  become: true
  changed_when: false
