- hosts: all
  become: yes
  roles:
    - role: microk8s

- hosts: control
  become: yes
  roles:
    - role: setup
    - role: prometheus
    - role: grafana

- hosts: workers
  become: yes
  roles:
    - role: join
